made timeline more responsive
IEEECS-VIT/hackbattle-24 pull request #25
Opened 2024-09-13 07:04 UTC by ashmitdudeja1107

2024-09-13 15:45 UTC, anshmehta7x requested changes
![image](https://github.com/user-attachments/assets/7f78385e-76ad-4f11-a82a-03de6edb9ab1)
what are these values lol

2024-09-13 15:45 UTC, anshmehta7x commented on src/app/timeline/page.js
![image](https://github.com/user-attachments/assets/db59c4c3-ee5b-4105-a44d-b8d50fcf6823)

?????????

2024-09-13 16:07 UTC, ashmitdudeja1107 commented on src/app/timeline/page.js
![Screenshot 2024-09-13 213438](https://github.com/user-attachments/assets/fd9740ee-9826-4296-a08b-a2ea7e8eff66)
if i change this ipad view background is changed

2024-09-14 15:28 UTC, anshmehta7x approved these changes

2024-09-14 15:28 UTC, merged